ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # IMU settings
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,   # use yaw
                  false, false, false,
                  false, false, true,   # use yaw rate
                  true, true, false]
    imu0_remove_gravitational_acceleration: true
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10

    # Odometry settings	
    odom0: /odom
    odom0_config: [false,  false,  false,    # X, Y position
                   false, false, false,     # yaw only
                   true,  true,  false,    # X, Y velocity
                   false, false, false,     # yaw rate
                   false, false, false]    # linear acceleration (not used)
    odom0_differential: false
    odom0_queue_size: 10 
